name: 🚀 Deploy Sandik to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Prepare SSH private key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: 🌐 Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Connect to EC2 and run deploy.sh
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "✅ Connected to EC2"

            cd /var/www/sandik || { echo "❌ Folder not found"; exit 1; }

            echo "▶️ Running deploy.sh"
            ./deploy.sh || { echo "❌ Deployment script failed"; exit 1; }

            echo "✅ Deployment completed"
          EOF
